# Generated by Django 4.2.2 on 2023-06-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_complaint_address_alter_complaint_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='summary',
            field=models.TextField(max_length=100),
        ),
    ]
