# Generated by Django 4.2.2 on 2023-06-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_complaint_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='i_agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='occupation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='redress',
            field=models.CharField(choices=[('R', 'REFUND'), ('X', 'EXCHANGE'), ('RR', 'REPAIR'), ('CN', 'CREDIT NOTE'), ('O', 'OTHER')], default='R', help_text='if other please state redress', max_length=5),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='summary',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
