# Generated by Django 4.2.2 on 2023-06-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_complaint_i_agree_alter_complaint_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='redress',
            field=models.CharField(choices=[('REFUND', 'REFUND'), ('EXCHANGE', 'EXCHANGE'), ('REPAIR', 'REPAIR'), ('CN', 'CREDIT NOTE'), ('OTHER', 'OTHER')], default='REFUND', help_text='if other please state redress', max_length=10),
        ),
    ]
