# Generated by Django 4.2.2 on 2023-06-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_complaint_redress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainthandling',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complainthandling',
            name='exhibits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complainthandling',
            name='investigating_officer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complainthandling',
            name='ministry_liaison',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complainthandling',
            name='officer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complainthandling',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
    ]
