# Generated by Django 4.2.2 on 2023-06-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_complainthandling_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='manufactured_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
