# Generated by Django 4.2.2 on 2023-06-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_complaint_manufactured_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('RATHER_NOT_SAY', 'RATHER NOT SAY')], default='RATHER_NOT_SAY', max_length=15),
        ),
    ]
