# Generated by Django 4.2.2 on 2023-06-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_complaint_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_purchased',
            field=models.DateField(blank=True, null=True),
        ),
    ]
